# Generated by Django 4.0.6 on 2022-07-26 08:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_user_email_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meteostations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='stations_counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1024)]),
        ),
        migrations.CreateModel(
            name='UserMeteostations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteostation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.meteostations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('uaccum', models.IntegerField()),
                ('photolight', models.IntegerField()),
                ('humground', models.IntegerField()),
                ('humair', models.FloatField()),
                ('tair', models.FloatField()),
                ('airpressure', models.FloatField()),
                ('tgroundsurface', models.FloatField()),
                ('tgrounddeep', models.FloatField()),
                ('wingspeed', models.FloatField()),
                ('wingdir', models.FloatField()),
                ('meteostation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.meteostations')),
            ],
        ),
    ]
